// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-bugs.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-bugs.ts
var STATUSES = ["new", "assigned", "in_progress", "testing", "resolved", "closed"];
var SEVERITIES = ["critical", "high", "medium", "low"];
var list_bugs_default = defineTool({
  name: "list_bugs",
  title: "List bugs",
  description: "List bug reports in Triage, optionally filtered by status, severity, or a text search.",
  inputSchema: {
    status: z.enum(STATUSES).optional().describe("Filter by bug status."),
    severity: z.enum(SEVERITIES).optional().describe("Filter by bug severity."),
    search: z.string().trim().min(1).optional().describe("Case-insensitive match on the bug title."),
    limit: z.number().int().min(1).max(100).optional().describe("Max number of bugs to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, severity, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("bugs").select("id, tracking_id, title, status, severity, assignee_id, reporter_id, created_at, updated_at, sla_deadline").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (status) query = query.eq("status", status);
    if (severity) query = query.eq("severity", severity);
    if (search) query = query.ilike("title", `%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { bugs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-bug.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_bug_default = defineTool2({
  name: "get_bug",
  title: "Get bug",
  description: "Fetch one bug by tracking ID (e.g. BUG-1234) or UUID, including its comments.",
  inputSchema: {
    bug: z2.string().trim().min(1).describe("Tracking ID or UUID of the bug.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ bug }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const isUuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(bug);
    const { data, error } = await supabase.from("bugs").select("*").eq(isUuid ? "id" : "tracking_id", bug).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No bug found for "${bug}"` }], isError: true };
    const { data: comments } = await supabase.from("comments").select("id, content, user_id, created_at").eq("bug_id", data.id).order("created_at", { ascending: true });
    const result = { ...data, comments: comments ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: { bug: result }
    };
  }
});

// src/lib/mcp/tools/create-bug.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var SEVERITIES2 = ["critical", "high", "medium", "low"];
var create_bug_default = defineTool3({
  name: "create_bug",
  title: "Create bug",
  description: "File a new bug report in Triage as the signed-in user.",
  inputSchema: {
    title: z3.string().trim().min(1).max(200).describe("Short summary of the bug."),
    description: z3.string().trim().min(1).max(5e3).describe("Detailed description of the issue."),
    severity: z3.enum(SEVERITIES2).optional().describe("Severity (defaults to medium)."),
    steps_to_reproduce: z3.string().trim().max(5e3).optional(),
    expected_behavior: z3.string().trim().max(2e3).optional(),
    actual_behavior: z3.string().trim().max(2e3).optional(),
    environment: z3.string().trim().max(200).optional().describe("e.g. Chrome 120, macOS 14")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("bugs").insert({
      title: input.title,
      description: input.description,
      severity: input.severity ?? "medium",
      steps_to_reproduce: input.steps_to_reproduce ?? null,
      expected_behavior: input.expected_behavior ?? null,
      actual_behavior: input.actual_behavior ?? null,
      environment: input.environment ?? null,
      reporter_id: ctx.getUserId()
    }).select("id, tracking_id, title, status, severity").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Created ${data.tracking_id}: ${data.title}` }],
      structuredContent: { bug: data }
    };
  }
});

// src/lib/mcp/tools/update-bug.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var STATUSES2 = ["new", "assigned", "in_progress", "testing", "resolved", "closed"];
var SEVERITIES3 = ["critical", "high", "medium", "low"];
var update_bug_default = defineTool4({
  name: "update_bug",
  title: "Update bug",
  description: "Update the status, severity, or assignee of an existing bug in Triage.",
  inputSchema: {
    bug: z4.string().trim().min(1).describe("Tracking ID or UUID of the bug."),
    status: z4.enum(STATUSES2).optional(),
    severity: z4.enum(SEVERITIES3).optional(),
    assignee_id: z4.string().uuid().nullable().optional().describe("User id to assign, or null to unassign.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ bug, status, severity, assignee_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const patch = {};
    if (status !== void 0) patch.status = status;
    if (severity !== void 0) patch.severity = severity;
    if (assignee_id !== void 0) patch.assignee_id = assignee_id;
    if (Object.keys(patch).length === 0) {
      return { content: [{ type: "text", text: "Nothing to update." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const isUuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(bug);
    const { data, error } = await supabase.from("bugs").update(patch).eq(isUuid ? "id" : "tracking_id", bug).select("id, tracking_id, title, status, severity, assignee_id").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No bug found for "${bug}"` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { bug: data }
    };
  }
});

// src/lib/mcp/tools/add-comment.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^3.25.76";
var add_comment_default = defineTool5({
  name: "add_comment",
  title: "Add comment",
  description: "Add a comment to a bug in Triage as the signed-in user.",
  inputSchema: {
    bug: z5.string().trim().min(1).describe("Tracking ID or UUID of the bug."),
    content: z5.string().trim().min(1).max(5e3).describe("Comment text.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ bug, content }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const isUuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(bug);
    const { data: target, error: lookupError } = await supabase.from("bugs").select("id, tracking_id").eq(isUuid ? "id" : "tracking_id", bug).maybeSingle();
    if (lookupError) return { content: [{ type: "text", text: lookupError.message }], isError: true };
    if (!target) return { content: [{ type: "text", text: `No bug found for "${bug}"` }], isError: true };
    const { data, error } = await supabase.from("comments").insert({ bug_id: target.id, content, user_id: ctx.getUserId() }).select("id, content, created_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Comment added to ${target.tracking_id}` }],
      structuredContent: { comment: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "gilgxaszyknetmsemvhw";
var mcp_default = defineMcp({
  name: "triage",
  title: "Triage",
  version: "0.1.0",
  instructions: "Tools for Triage, a team bug tracker. Use `list_bugs` to browse or search bugs, `get_bug` for full detail plus comments, `create_bug` to file a report, `update_bug` to change status/severity/assignee, and `add_comment` to discuss a bug. Bugs are referenced by tracking ID (e.g. BUG-1234) or UUID.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_bugs_default, get_bug_default, create_bug_default, update_bug_default, add_comment_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
